#!/usr/bin/env bash

WebKitTools/Scripts/build-webkit --clutter --minimal --debug --with-target=quartz PKG_CONFIG_PATH="/opt/local/lib/pkgconfig:/usr/local/lib/pkgconfig" CPPFLAGS="-I/opt/local/include" LDFLAGS="-L/opt/local/lib"
